--------------------------------------------------------
--  DDL for Table STAGIAIRE
--------------------------------------------------------

  CREATE TABLE "ANONYMOUS"."STAGIAIRE" 
   (	"NUM_STAGIAIRE" CHAR(5 BYTE), 
	"NOM_STAGIAIRE" CHAR(15 BYTE), 
	"PRENOM_STAGIAIRE" CHAR(15 BYTE), 
	"SEXE_STAGIAIRE" CHAR(1 BYTE), 
	"DNAISS_STAGIAIRE" DATE, 
	"DIPLO_STAGIAIRE" CHAR(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index STAGIAIRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANONYMOUS"."STAGIAIRE_PK" ON "ANONYMOUS"."STAGIAIRE" ("NUM_STAGIAIRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  Constraints for Table STAGIAIRE
--------------------------------------------------------

  ALTER TABLE "ANONYMOUS"."STAGIAIRE" MODIFY ("NUM_STAGIAIRE" NOT NULL ENABLE);
  ALTER TABLE "ANONYMOUS"."STAGIAIRE" MODIFY ("NOM_STAGIAIRE" NOT NULL ENABLE);
  ALTER TABLE "ANONYMOUS"."STAGIAIRE" MODIFY ("PRENOM_STAGIAIRE" NOT NULL ENABLE);
  ALTER TABLE "ANONYMOUS"."STAGIAIRE" MODIFY ("SEXE_STAGIAIRE" NOT NULL ENABLE);
  ALTER TABLE "ANONYMOUS"."STAGIAIRE" MODIFY ("DNAISS_STAGIAIRE" NOT NULL ENABLE);
  ALTER TABLE "ANONYMOUS"."STAGIAIRE" MODIFY ("DIPLO_STAGIAIRE" NOT NULL ENABLE);
  ALTER TABLE "ANONYMOUS"."STAGIAIRE" ADD CONSTRAINT "STAGIAIRE_PK" PRIMARY KEY ("NUM_STAGIAIRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;

--------------------------------------------------------
--  DDL for Table STAGE
--------------------------------------------------------

  CREATE TABLE "ANONYMOUS"."STAGE" 
   (	"CODE_STAGE" CHAR(5 BYTE), 
	"TYPE_STAGE" CHAR(5 BYTE), 
	"DEBUT_STAGE" DATE, 
	"FIN_STAGE" DATE, 
	"NBPLACE_STAGE" NUMBER(2,0), 
	"NBINSCRIT_STAGE" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index STAGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANONYMOUS"."STAGE_PK" ON "ANONYMOUS"."STAGE" ("CODE_STAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  Constraints for Table STAGE
--------------------------------------------------------

  ALTER TABLE "ANONYMOUS"."STAGE" MODIFY ("CODE_STAGE" NOT NULL ENABLE);
  ALTER TABLE "ANONYMOUS"."STAGE" MODIFY ("TYPE_STAGE" NOT NULL ENABLE);
  ALTER TABLE "ANONYMOUS"."STAGE" MODIFY ("DEBUT_STAGE" NOT NULL ENABLE);
  ALTER TABLE "ANONYMOUS"."STAGE" MODIFY ("FIN_STAGE" NOT NULL ENABLE);
  ALTER TABLE "ANONYMOUS"."STAGE" MODIFY ("NBPLACE_STAGE" NOT NULL ENABLE);
  ALTER TABLE "ANONYMOUS"."STAGE" MODIFY ("NBINSCRIT_STAGE" NOT NULL ENABLE);
  ALTER TABLE "ANONYMOUS"."STAGE" ADD CONSTRAINT "STAGE_PK" PRIMARY KEY ("CODE_STAGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;

--------------------------------------------------------
--  DDL for Table INSCRIPTION
--------------------------------------------------------

  CREATE TABLE "ANONYMOUS"."INSCRIPTION" 
   (	"CODE_STAGE" CHAR(5 BYTE), 
	"NUM_STAGIAIRE" CHAR(5 BYTE), 
	"DATE_INSCRIP" DATE, 
	"STATUT_INSCRIP" CHAR(5 BYTE), 
	"CODE_POSITION" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  DDL for Index INSCRIPTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANONYMOUS"."INSCRIPTION_PK" ON "ANONYMOUS"."INSCRIPTION" ("CODE_STAGE", "NUM_STAGIAIRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" ;
--------------------------------------------------------
--  Constraints for Table INSCRIPTION
--------------------------------------------------------

  ALTER TABLE "ANONYMOUS"."INSCRIPTION" MODIFY ("CODE_STAGE" NOT NULL ENABLE);
  ALTER TABLE "ANONYMOUS"."INSCRIPTION" MODIFY ("NUM_STAGIAIRE" NOT NULL ENABLE);
  ALTER TABLE "ANONYMOUS"."INSCRIPTION" MODIFY ("DATE_INSCRIP" NOT NULL ENABLE);
  ALTER TABLE "ANONYMOUS"."INSCRIPTION" MODIFY ("STATUT_INSCRIP" NOT NULL ENABLE);
  ALTER TABLE "ANONYMOUS"."INSCRIPTION" MODIFY ("CODE_POSITION" NOT NULL ENABLE);
  ALTER TABLE "ANONYMOUS"."INSCRIPTION" ADD CONSTRAINT "INSCRIPTION_PK" PRIMARY KEY ("CODE_STAGE", "NUM_STAGIAIRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INSCRIPTION
--------------------------------------------------------

  ALTER TABLE "ANONYMOUS"."INSCRIPTION" ADD CONSTRAINT "FK_STAGE" FOREIGN KEY ("CODE_STAGE")
	  REFERENCES "ANONYMOUS"."STAGE" ("CODE_STAGE") ENABLE;
  ALTER TABLE "ANONYMOUS"."INSCRIPTION" ADD CONSTRAINT "FK_STAGIAIRE" FOREIGN KEY ("NUM_STAGIAIRE")
	  REFERENCES "ANONYMOUS"."STAGIAIRE" ("NUM_STAGIAIRE") ENABLE;